# base image
FROM nginx:1.15.0-alpine

# remove .conf file from image
RUN rm /etc/nginx/conf.d/default.conf
# copy from local folder to docker image folder
COPY nginx.conf /etx/nginx/conf.d

# create php file
RUN mkdir /var/www/html -p && touch /var/www/html/index.php